# Generated by carnix 0.10.0: cargo-generate-nixfile generate-nixfile --src ./. --standalone
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# kamikaze-1.0.0

    crates.kamikaze."1.0.0" = deps: { features?(features_.kamikaze."1.0.0" deps {}) }: buildRustCrate {
      crateName = "kamikaze";
      version = "1.0.0";
      authors = [ "Ente <ducksource@duckpond.ch>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."exec"."${deps."kamikaze"."1.0.0"."exec"}" deps)
        (cratesIO.crates."users"."${deps."kamikaze"."1.0.0"."users"}" deps)
      ]);
    };
    features_.kamikaze."1.0.0" = deps: f: updateFeatures f (rec {
      exec."${deps.kamikaze."1.0.0".exec}".default = true;
      kamikaze."1.0.0".default = (f.kamikaze."1.0.0".default or true);
      users."${deps.kamikaze."1.0.0".users}".default = true;
    }) [
      (cratesIO.features_.exec."${deps."kamikaze"."1.0.0"."exec"}" deps)
      (cratesIO.features_.users."${deps."kamikaze"."1.0.0"."users"}" deps)
    ];


# end

  };

  kamikaze = crates.crates.kamikaze."1.0.0" deps;
  __all = [ (kamikaze {}) ];
  deps.errno."0.2.4" = {
    errno_dragonfly = "0.1.1";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.errno_dragonfly."0.1.1" = {
    libc = "0.2.54";
    gcc = "0.3.55";
  };
  deps.exec."0.3.1" = {
    errno = "0.2.4";
    libc = "0.2.54";
  };
  deps.gcc."0.3.55" = {};
  deps.kamikaze."1.0.0" = {
    exec = "0.3.1";
    users = "0.9.1";
  };
  deps.libc."0.2.54" = {};
  deps.users."0.9.1" = {
    libc = "0.2.54";
  };
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
}
