# Generated by carnix 0.10.0: cargo-generate-nixfile generate-nixfile --src ./. --standalone
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# kamikaze-0.1.0

    crates.kamikaze."0.1.0" = deps: { features?(features_.kamikaze."0.1.0" deps {}) }: buildRustCrate {
      crateName = "kamikaze";
      version = "0.1.0";
      authors = [ "Ente <ducksource@duckpond.ch>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
    };
    features_.kamikaze."0.1.0" = deps: f: updateFeatures f (rec {
      kamikaze."0.1.0".default = (f.kamikaze."0.1.0".default or true);
    }) [];


# end

  };

  kamikaze = crates.crates.kamikaze."0.1.0" deps;
  __all = [ (kamikaze {}) ];
  deps.kamikaze."0.1.0" = {};
}
